package gui;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;

import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;

import core.Lexic;
import core.Syntatic;

/**
 *
 * @author 08062671
 */
public class PGrafica extends javax.swing.JFrame {

    /**
     * Creates new form PGrafica
     */
    public PGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelArquivo = new javax.swing.JLabel();
        jTextFieldArquivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCodigo = new javax.swing.JTextArea();
        jLabelLinhaColuna = new javax.swing.JLabel();
        jLabelErros = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaErros = new javax.swing.JTextArea();
        jButtonCompilar = new javax.swing.JButton();
        jLabelCompilar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemSalvar = new javax.swing.JMenuItem();
        jMenuItemSalvarComo = new javax.swing.JMenuItem();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelArquivo.setText("Arquivo:");

        jTextFieldArquivo.setEditable(false);

        jTextAreaCodigo.setColumns(20);
        jTextAreaCodigo.setRows(5);
        jTextAreaCodigo.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent arg0) {
                if (arg0.getKeyChar() == '\t') {
                    jTextAreaCodigo.setText(jTextAreaCodigo.getText().replace("\t", "  "));
                }
            }

            @Override
            public void keyReleased(KeyEvent arg0) {

            }

            @Override
            public void keyPressed(KeyEvent arg0) {

            }
        });
        jScrollPane1.setViewportView(jTextAreaCodigo);

        jLabelLinhaColuna.setText("Linhas, Colunas");

        jLabelErros.setText("Erros:");

        jTextAreaErros.setColumns(20);
        jTextAreaErros.setRows(5);
        jScrollPane2.setViewportView(jTextAreaErros);

        jButtonCompilar.setText("Compilar");
        jButtonCompilar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCompilation();
            }
        });

        jLabelCompilar.setText("jLabel2");

        jMenuArquivo.setText("Arquivo");

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenuItemAbrir.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_DOWN_MASK));
        jMenuArquivo.add(jMenuItemAbrir);

        jMenuItemSalvar.setText("Salvar");
        jMenuItemSalvar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                try {
                    if (currentFile == null) {
                        JFileChooser jfc = new JFileChooser();
                        jfc.showSaveDialog(PGrafica.this);
                        currentFile = jfc.getSelectedFile();

                        setTitle(currentFile.getAbsolutePath());
                    }
                    PrintWriter pw = new PrintWriter(new FileWriter(currentFile));
                    for (String line : jTextAreaCodigo.getText().split("\n")) {
                        pw.println(line);
                    }
                    pw.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        jMenuItemSalvar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK));
        jMenuArquivo.add(jMenuItemSalvar);

        jMenuItemSalvarComo.setText("Salvar Como");
        jMenuItemSalvarComo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                JFileChooser jfc = new JFileChooser();
                jfc.showSaveDialog(PGrafica.this);
            }
        });
        jMenuArquivo.add(jMenuItemSalvarComo);

        jMenuItemFechar.setText("Fechar");
        jMenuArquivo.add(jMenuItemFechar);

        jMenuItemSair.setText("Sair");
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuSobre.setText("Sobre");
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelArquivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelLinhaColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelErros)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(99, 99, 99)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonCompilar)
                                                        .addComponent(jLabelCompilar))))
                                                        .addContainerGap(23, Short.MAX_VALUE))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelArquivo)
                                .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLinhaColuna)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCompilar)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelCompilar)))
                                                .addContainerGap(46, Short.MAX_VALUE))
                );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed

        JFileChooser abrirArquivo = new JFileChooser("./res");

        if(abrirArquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            currentFile = abrirArquivo.getSelectedFile();
            try {
                jTextAreaCodigo.setText("");
                BufferedReader br = new BufferedReader(new FileReader(currentFile));
                String line;
                while((line = br.readLine()) != null) {
                    jTextAreaCodigo.append(line + "\n");
                }
                br.close();

                setTitle(currentFile.getAbsolutePath());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jMenuItemAbrirActionPerformed


    private File currentFile;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCompilar;
    private javax.swing.JLabel jLabelArquivo;
    private javax.swing.JLabel jLabelCompilar;
    private javax.swing.JLabel jLabelErros;
    private javax.swing.JLabel jLabelLinhaColuna;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSalvar;
    private javax.swing.JMenuItem jMenuItemSalvarComo;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCodigo;
    private javax.swing.JTextArea jTextAreaErros;
    private javax.swing.JTextField jTextFieldArquivo;
    // End of variables declaration//GEN-END:variables

    public JTextArea getCodeArea() {
        return jTextAreaCodigo;
    }

    public JTextArea getErrorArea() {
        return jTextAreaErros;
    }

    private void startCompilation() {
    	Lexic.newInstance();
        Lexic c = Lexic.getInstance();
        c.setSourceFile(currentFile);
        //                c.startAnalysis();
        c.setWindow(PGrafica.this);
        Syntatic.newInstance();
        Syntatic s = Syntatic.getInstance();
        s.setWindow(PGrafica.this);
        c.setSyntatic(s);
        s.setCore(c);
        Thread sThread = new Thread(s);
        s.setThread(sThread);
        sThread.start();
    }
}
